# Diff Configuration.

#####################Global config #########################

# The number of threads that check the data. The number of connections to the upstream and downstream databases will be slightly larger than this value.
check-thread-count = 4

# When on, if there is an inconsistency in the table, the SQL statement used to fix it is output.
export-fix-sql = true

# Comparing only table schema without comparing data
check-struct-only = false


#####################Datasource config #########################
[data-sources]
[data-sources.mysql]
      host = "<HOST_PD3_PRIVATE_IP>"
      port = 3306
      user = "ins"
      password = "q1w2e3R4_"

      #(Optional) Use mapping rules to match multiple shards upstream, where rule1 and rule2 are defined in the Routes configuration column below
      route-rules = ["rule1"]

[data-sources.tidb]
      host = "<HOST_DB1_PRIVATE_IP>"
      port = 4000
      user = "ins"
      password = "q1w2e3R4_"

#######################Routes ###########################
# If You Need to Compare the Data of a Large Number of Tables with Different Library Names or Table Names, or to Verify the Data of Multiple Upstream Sharded Sharded Table and Downstream Combined Table, You Can Use Table-rule to Set the Mapping Relationship
# You Can Configure Only Schema or Table Mapping Relationships, or Both
[routes]
[routes.rule1] # rule1 is a custom id that uniquely identifies this configuration and is used in data-sources.route-rules above
schema-pattern = "test1"      # Match the library name of the data source. Wildcards "*" and "?" are supported
target-schema = "test1"         # Target library name

#####################Task config #########################
# Configuration Table in *Target Database* That Needs to Be Compared
[task]
      output-dir = "./output"
      source-instances = ["mysql"]
      target-instance = "tidb"
      target-check-tables = ["test1.*"]